version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:30"
      timezone: "Europe/Brussels"
    labels:
      - "dependencies"
      - "automated"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Europe/Brussels"
    labels:
      - "dependencies"
      - "github-actions"
