[mypy]
ignore_missing_imports = True
exclude = src/iints/templates

[mypy-rich.*]
ignore_errors = True

[mypy-typer.*]
ignore_errors = True

[mypy-torch.*]
ignore_errors = True

[mypy-simglucose.*]
ignore_errors = True

[mypy-matplotlib.*]
ignore_errors = True

[mypy-iints.core.supervisor]
disallow_untyped_defs = True
disallow_any_generics = True
no_implicit_optional = True
warn_return_any = True

[mypy-iints.core.safety.config]
disallow_untyped_defs = True
disallow_any_generics = True
no_implicit_optional = True
warn_return_any = True

[mypy-iints.core.safety.input_validator]
disallow_untyped_defs = True
disallow_any_generics = True
no_implicit_optional = True
warn_return_any = True

[mypy-iints.core.simulator]
check_untyped_defs = True
