from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EvidenceConnector:
    """One external research evidence source surfaced by the desktop app."""

    key: str
    title: str
    category: str
    integration_status: str
    why_it_matters: str
    app_use: str
    primary_url: str
    docs_url: str
    default_query: str
    integration_level: str = "portal"
    access_mode: str = "Official portal link"
    writes_local_evidence: bool = False
    provenance_note: str = "External evidence requires claim-level human review before publication."


def list_evidence_connectors() -> list[EvidenceConnector]:
    """Return curated, allowlisted evidence sources for the native workbench.

    These entries are metadata only. The desktop shell may open their official
    documentation or portals in the system browser, but deterministic SDK
    outputs remain the source of truth for generated reports.
    """

    return [
        EvidenceConnector(
            key="ro-crate",
            title="RO-Crate 1.2",
            category="Research provenance",
            integration_status="Integrated academic package export",
            why_it_matters="Packages run metadata, files, checksums, software context, and evidence references as JSON-LD.",
            app_use="The Reproducibility package panel writes ro-crate-metadata.json beside a completed run.",
            primary_url="https://www.researchobject.org/ro-crate/",
            docs_url="https://www.researchobject.org/ro-crate/specification/1.2/introduction.html",
            default_query="RO-Crate 1.2 specification",
            integration_level="integrated",
            access_mode="Local exporter following the public specification",
            writes_local_evidence=True,
            provenance_note="The export is RO-Crate-compatible metadata; it is not a repository deposit or peer review.",
        ),
        EvidenceConnector(
            key="alphafold-db",
            title="AlphaFold Protein Structure Database",
            category="Structural biology",
            integration_status="Bundled 3D assets + PAE evidence",
            why_it_matters="Shows predicted protein structure for insulin, glucagon, INSR, GLUT4, and GCGR.",
            app_use="Protein evidence cards, mmCIF opening, PAE matrix links, and molecular context for SDK formulas.",
            primary_url="https://alphafold.ebi.ac.uk/",
            docs_url="https://alphafold.ebi.ac.uk/",
            default_query="P01308 insulin",
            integration_level="integrated",
            access_mode="Live API/cache plus local mmCIF, PNG, and optional PAE artifacts",
            writes_local_evidence=True,
            provenance_note="pLDDT and PAE describe prediction confidence, not pathogenicity or metabolic severity.",
        ),
        EvidenceConnector(
            key="ensembl-vep-alphamissense",
            title="Ensembl VEP + AlphaMissense",
            category="Variant interpretation",
            integration_status="Recommended next live connector",
            why_it_matters="Annotates variants and can include AlphaMissense scores for missense pathogenicity context.",
            app_use="Variant evidence panel for mutation-to-simulation workflows such as INSR V938M.",
            primary_url="https://rest.ensembl.org/",
            docs_url="https://rest.ensembl.org/documentation/info/vep_id_post",
            default_query="INSR V938M / rsID",
            integration_level="planned",
        ),
        EvidenceConnector(
            key="open-targets",
            title="Open Targets Platform",
            category="Target-disease evidence",
            integration_status="Recommended evidence graph connector",
            why_it_matters="Links targets, diseases, drugs, genetic evidence, tractability, and safety evidence.",
            app_use="Evidence graph cards for INSR, SLC2A4, GCGR, insulin resistance, and diabetes phenotypes.",
            primary_url="https://platform.opentargets.org/",
            docs_url="https://platform-docs.opentargets.org/data-access/graphql-api",
            default_query="SLC2A4 diabetes mellitus",
            integration_level="planned",
        ),
        EvidenceConnector(
            key="reactome",
            title="Reactome",
            category="Pathways",
            integration_status="Recommended pathway connector",
            why_it_matters="Expert-authored pathway knowledge for insulin signalling, glucagon signalling, and glucose metabolism.",
            app_use="Pathway panel explaining which biology sits behind each SDK equation block.",
            primary_url="https://reactome.org/",
            docs_url="https://reactome.org/dev/content-service",
            default_query="Insulin receptor signalling cascade",
            integration_level="planned",
        ),
        EvidenceConnector(
            key="rcsb-pdb",
            title="RCSB PDB",
            category="Experimental structures",
            integration_status="Recommended structure validation connector",
            why_it_matters="Provides experimental structures and metadata to compare against AlphaFold predictions.",
            app_use="Structure provenance view: predicted AlphaFold vs experimentally solved PDB evidence.",
            primary_url="https://www.rcsb.org/",
            docs_url="https://data.rcsb.org/",
            default_query="insulin receptor structure",
            integration_level="portal",
        ),
        EvidenceConnector(
            key="uniprot",
            title="UniProt",
            category="Protein annotation",
            integration_status="Recommended protein summary connector",
            why_it_matters="Canonical protein function, sequence, domains, features, variants, and cross-references.",
            app_use="Protein cards next to the 3D viewer and SDK formula links.",
            primary_url="https://www.uniprot.org/",
            docs_url="https://www.uniprot.org/help/api_queries",
            default_query="P01308",
            integration_level="portal",
        ),
        EvidenceConnector(
            key="human-protein-atlas",
            title="Human Protein Atlas",
            category="Tissue/protein expression",
            integration_status="Recommended expression evidence connector",
            why_it_matters="Protein and RNA expression evidence across tissues, useful for compartment plausibility.",
            app_use="Tissue expression cards for GLUT4, INSR, and GCGR.",
            primary_url="https://www.proteinatlas.org/",
            docs_url="https://www.proteinatlas.org/about/help/dataaccess",
            default_query="SLC2A4",
            integration_level="portal",
        ),
        EvidenceConnector(
            key="gtex",
            title="GTEx Portal API",
            category="Tissue RNA expression / eQTL",
            integration_status="Partially integrated via expression renders",
            why_it_matters="Human tissue expression and eQTL context for anatomy-aware model explanations.",
            app_use="Interactive tissue-expression plots and tissue-specific resistance stress tests.",
            primary_url="https://gtexportal.org/",
            docs_url="https://gtexportal.org/api/v2/docs",
            default_query="SLC2A4 skeletal muscle",
            integration_level="partial",
            access_mode="Live GTEx query with local Plotly expression output",
            writes_local_evidence=True,
            provenance_note="Expression context informs interpretation but does not automatically set physiology parameters.",
        ),
        EvidenceConnector(
            key="chembl",
            title="ChEMBL",
            category="Pharmacology",
            integration_status="Partially integrated molecule lookup",
            why_it_matters="Drug and molecule metadata for insulin analogues, mechanisms, and pharmacology context.",
            app_use="Insulin analogue cards linked to SDK PK/PD parameters such as absorption delay and tmax.",
            primary_url="https://www.ebi.ac.uk/chembl/",
            docs_url="https://chembl.gitbook.io/chembl-interface-documentation/web-services/chembl-data-web-services",
            default_query="insulin lispro",
            integration_level="partial",
            access_mode="Live ChEMBL metadata lookup with explicit SDK PK scenario mapping",
            provenance_note="Chemical identity and literature context do not validate a PK parameter without manual review.",
        ),
        EvidenceConnector(
            key="clinpgx-pharmgkb",
            title="ClinPGx / PharmGKB",
            category="Pharmacogenomics",
            integration_status="Recommended cautious connector",
            why_it_matters="Pharmacogenomics annotations, pathways, chemicals, genes, and clinical annotation context.",
            app_use="Research-only pharmacogenomics context cards; never dosing guidance.",
            primary_url="https://api.pharmgkb.org/",
            docs_url="https://api.pharmgkb.org/swagger/",
            default_query="INSR pharmacogenomics",
            integration_level="portal",
        ),
        EvidenceConnector(
            key="biomodels",
            title="BioModels",
            category="Mathematical model provenance",
            integration_status="Official model library; import planned",
            why_it_matters="Curated computational biology models and model metadata.",
            app_use="Model evidence library for ODE and glucose-insulin model provenance.",
            primary_url="https://www.biomodels.org/",
            docs_url="https://www.ebi.ac.uk/biostudies/BioModels/help",
            default_query="glucose insulin model",
            integration_level="planned",
            provenance_note="BioModels is migrating to BioStudies; the workbench does not yet import or execute deposited models.",
        ),
        EvidenceConnector(
            key="libroadrunner",
            title="libRoadRunner",
            category="Executable biochemical kinetics",
            integration_status="Integrated optional SBML execution engine",
            why_it_matters="Runs independent SBML reaction-network and ODE models for explicit cross-model checks.",
            app_use="The Mechanistic Reference Model Lab inspects local SBML safely and writes isolated time-course evidence.",
            primary_url="https://libroadrunner.readthedocs.io/",
            docs_url="https://libroadrunner.readthedocs.io/en/latest/tutorial/running_simulations.html",
            default_query="SBML time-course simulation",
            integration_level="integrated",
            access_mode="Local optional binary engine; structural inspection works without it",
            writes_local_evidence=True,
            provenance_note=(
                "Execution success is not biological validation; model units and population assumptions require review."
            ),
        ),
        EvidenceConnector(
            key="copasi",
            title="COPASI",
            category="Biochemical sensitivity and calibration",
            integration_status="Integrated task inspection; explicit CopasiSE execution",
            why_it_matters="Supports ODE, SDE, stochastic kinetics, parameter scans, sensitivity analysis, and estimation.",
            app_use="Inspect configured sensitivity/estimation tasks and run reviewed scheduled tasks as separate evidence.",
            primary_url="https://copasi.org/",
            docs_url="https://copasi.org/Support/User_Manual/Model_Creation/Commandline_Version_and_Commandline_Options/",
            default_query="SBML parameter estimation sensitivity analysis",
            integration_level="integrated",
            access_mode="Safe local COPASI-ML inspection with opt-in CopasiSE batch execution",
            writes_local_evidence=True,
            provenance_note="IINTS never generates an objective or silently imports fitted parameters into a patient model.",
        ),
        EvidenceConnector(
            key="opencor-physiome",
            title="OpenCOR + Physiome Model Repository",
            category="Whole-body physiology reference models",
            integration_status="Integrated CellML inspection and OpenCOR validation",
            why_it_matters="Provides executable CellML ODE/DAE models and public endocrine, metabolism, and PK/PD models.",
            app_use="Inspect local CellML and validate it with OpenCOR while keeping imports and mappings explicit.",
            primary_url="https://models.physiomeproject.org/cellml",
            docs_url="https://opencor.ws/user/plugins/simulation/simulationExperimentView.html",
            default_query="diabetes glucose insulin CellML",
            integration_level="integrated",
            access_mode="Safe local CellML inspection with optional OpenCOR CellMLTools validation",
            writes_local_evidence=True,
            provenance_note=(
                "Repository curation, imports, units, and biological suitability must be checked per model; "
                "OpenCOR validation is not biological validation."
            ),
        ),
        EvidenceConnector(
            key="fmi-fmpy",
            title="FMI + FMPy",
            category="Device physics and co-simulation",
            integration_status="Integrated static FMU inspection; trusted FMPy execution",
            why_it_matters="FMI can couple dynamic device models with physiology through Model Exchange or Co-Simulation.",
            app_use="Inspect FMU metadata safely, then optionally run reviewed device-physics FMUs through FMPy.",
            primary_url="https://fmi-standard.org/docs/3.0.2/",
            docs_url="https://fmpy.readthedocs.io/en/latest/tutorial/",
            default_query="FMI co-simulation medical pump model",
            integration_level="integrated",
            access_mode="Static ZIP/XML inspection by default; native execution requires explicit trust",
            writes_local_evidence=True,
            provenance_note=(
                "FMI does not sandbox native code. An FMU is only as realistic as its equations, parameters, units, "
                "solver, provenance, and bench-validation evidence."
            ),
        ),
        EvidenceConnector(
            key="bindingdb",
            title="BindingDB",
            category="Experimental binding chemistry",
            integration_status="Integrated read-only UniProt affinity evidence",
            why_it_matters="Provides measured protein-ligand affinity records that can complement predicted structures.",
            app_use="Export measured affinity records and assay metadata beside AlphaFold structures.",
            primary_url="https://www.bindingdb.org/rwd/bind/index.jsp",
            docs_url="https://www.bindingdb.org/rwd/bind/BindingDBRESTfulAPI.jsp",
            default_query="insulin receptor binding affinity",
            integration_level="integrated",
            access_mode="Read-only BindingDB REST query over verified TLS with local CSV/JSON evidence",
            writes_local_evidence=True,
            provenance_note="Kd, Ki, and IC50 are assay-specific and cannot be treated as interchangeable physiological effects.",
        ),
        EvidenceConnector(
            key="string-db",
            title="STRING DB",
            category="Protein interaction networks",
            integration_status="Partially integrated via pathway renders",
            why_it_matters="Protein-protein interaction networks for insulin and glucagon signalling cascades.",
            app_use="Network evidence panels for insulin-cascade and glucagon-rescue diagrams.",
            primary_url="https://string-db.org/",
            docs_url="https://string-db.org/help/api/",
            default_query="INSR IRS1 PIK3CA AKT1 SLC2A4",
            integration_level="partial",
            access_mode="Live STRING API image retrieval with local network output",
            writes_local_evidence=True,
        ),
        EvidenceConnector(
            key="clinvar",
            title="ClinVar / NCBI Clinical Tables",
            category="Variant evidence",
            integration_status="Partially integrated via mutation examples",
            why_it_matters="Public variant assertions and variant search metadata for genomic context.",
            app_use="Mutation lookup companion for the genomics simulation panel.",
            primary_url="https://www.ncbi.nlm.nih.gov/clinvar/",
            docs_url="https://clinicaltables.nlm.nih.gov/apidoc/variants/v3/doc.html",
            default_query="INSR V938M",
            integration_level="partial",
            access_mode="Live NCBI/ClinVar lookup used as research context",
            provenance_note="ClinVar assertions can conflict or change and never become a physiological scalar automatically.",
        ),
        EvidenceConnector(
            key="fair4rs",
            title="FAIR Principles for Research Software (FAIR4RS)",
            category="Research software governance",
            integration_status="Implemented as project guidance and audit criteria",
            why_it_matters="Makes research software more findable, accessible, interoperable, and reusable.",
            app_use="Guides citation, versioning, licensing, provenance, and reproducibility checks in academic exports.",
            primary_url="https://www.nature.com/articles/s41597-022-01710-x",
            docs_url="https://www.nature.com/articles/s41597-022-01710-x",
            default_query="FAIR Principles for Research Software",
            integration_level="partial",
            access_mode="Local governance checks linked to the published principles",
            writes_local_evidence=True,
            provenance_note="The SDK is FAIR-oriented; this label is not an external FAIR certification.",
        ),
        EvidenceConnector(
            key="sed-ml",
            title="SED-ML",
            category="Simulation reproducibility",
            integration_status="Planned standards-based simulation export",
            why_it_matters="Describes models, simulation tasks, algorithms, and outputs in a machine-readable format.",
            app_use="Future export path for portable protocol definitions alongside IINTS run metadata.",
            primary_url="https://sed-ml.org/",
            docs_url="https://sed-ml.org/",
            default_query="SED-ML Level 1 Version 5",
            integration_level="planned",
            provenance_note="No SED-ML file is generated yet; current reproducibility uses IINTS run metadata and RO-Crate.",
        ),
        EvidenceConnector(
            key="sbml",
            title="SBML",
            category="Computational model exchange",
            integration_status="Integrated local inspection; optional execution",
            why_it_matters="Provides a widely used machine-readable representation for computational biological models.",
            app_use="The Mechanistic Reference Model Lab inspects local SBML and can execute it independently through libRoadRunner.",
            primary_url="https://sbml.org/",
            docs_url="https://sbml.org/documents/specifications/",
            default_query="SBML Level 3 Version 2 Core",
            integration_level="integrated",
            access_mode="Safe local XML inspection with optional isolated time-course execution",
            writes_local_evidence=True,
            provenance_note=(
                "Current IINTS patient models remain Python implementations and are not claimed to be SBML-compatible; "
                "external model units and assumptions require explicit review."
            ),
        ),
        EvidenceConnector(
            key="pubmed",
            title="PubMed",
            category="Literature search",
            integration_status="Official literature portal; structured capture planned",
            why_it_matters="Supports traceable primary-literature discovery for physiological and evaluation claims.",
            app_use="Open literature searches now; a future connector can save query, PMID, date, and selection reason.",
            primary_url="https://pubmed.ncbi.nlm.nih.gov/",
            docs_url="https://www.ncbi.nlm.nih.gov/books/NBK25501/",
            default_query="type 1 diabetes glucose insulin model validation",
            integration_level="planned",
        ),
        EvidenceConnector(
            key="clinicaltrials-gov",
            title="ClinicalTrials.gov",
            category="Study registry",
            integration_status="Official registry link; no automated inference",
            why_it_matters="Provides study-design and outcome context for diabetes-technology research questions.",
            app_use="Use as external study context, never as automatic clinical validation of a simulation result.",
            primary_url="https://clinicaltrials.gov/",
            docs_url="https://clinicaltrials.gov/data-api/about-api",
            default_query="type 1 diabetes automated insulin delivery",
            integration_level="portal",
        ),
        EvidenceConnector(
            key="zenodo",
            title="Zenodo",
            category="Archiving and DOI",
            integration_status="Manual deposit only",
            why_it_matters="Can archive release artifacts and issue a DOI for a reviewed public research package.",
            app_use="Open the official repository after privacy, licensing, and completeness review; the SDK never auto-uploads data.",
            primary_url="https://zenodo.org/",
            docs_url="https://developers.zenodo.org/",
            default_query="software deposit DOI",
            integration_level="portal",
            provenance_note="Manual review is mandatory before any deposit; no credentials or uploads are handled by this connector.",
        ),
    ]
