"""Evidence-backed scientific figures for IINTS-AF.

Result figures in this module never invent measurements. Evidence-dependent
plots require an explicit artifact and fail closed when it is absent. The one
figure that does not require data is the GlucoFM method schematic; it is
labelled as architecture, not as an experimental result.
"""

from __future__ import annotations

import base64
from dataclasses import dataclass
from hashlib import sha256
from html import escape
from pathlib import Path
from typing import Any, Sequence, cast

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.axes import Axes
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch
from matplotlib.projections.polar import PolarAxes
import numpy as np
import pandas as pd

from iints.research.foundation_arena import run_foundation_model_arena


def apply_scientific_plot_style() -> None:
    """Apply a restrained, publication-oriented matplotlib style."""

    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["DejaVu Sans", "Helvetica Neue", "Arial"],
            "axes.edgecolor": "#64748B",
            "axes.linewidth": 0.9,
            "axes.titlesize": 12,
            "axes.titleweight": "bold",
            "axes.labelsize": 10,
            "axes.labelcolor": "#1E293B",
            "xtick.labelsize": 8.5,
            "ytick.labelsize": 8.5,
            "xtick.color": "#475569",
            "ytick.color": "#475569",
            "grid.color": "#CBD5E1",
            "grid.linestyle": "--",
            "grid.linewidth": 0.7,
            "legend.fontsize": 8.5,
            "legend.framealpha": 0.95,
            "figure.facecolor": "#FFFFFF",
        }
    )


def _optional_path(path: Path | None) -> str | None:
    return str(path) if path is not None else None


@dataclass(frozen=True)
class ScientificVisualizationArtifacts:
    """Files generated by the evidence-aware visualization suite."""

    output_dir: Path
    arena_radar_png: Path | None
    confounder_cosine_png: Path | None
    glucofm_decomposition_png: Path
    cgmacros_dualsensor_png: Path | None
    fda_safety_timeline_png: Path | None
    interactive_dashboard_html: Path

    def to_dict(self) -> dict[str, Any]:
        return {
            "output_dir": str(self.output_dir),
            "arena_radar_png": _optional_path(self.arena_radar_png),
            "confounder_cosine_png": _optional_path(self.confounder_cosine_png),
            "glucofm_decomposition_png": str(self.glucofm_decomposition_png),
            "cgmacros_dualsensor_png": _optional_path(self.cgmacros_dualsensor_png),
            "fda_safety_timeline_png": _optional_path(self.fda_safety_timeline_png),
            "interactive_dashboard_html": str(self.interactive_dashboard_html),
        }


def _resolve_output(output_path: Path | str) -> Path:
    output = Path(output_path).expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    return output


def _read_evidence_table(path: Path | str) -> tuple[pd.DataFrame, Path, str]:
    source = Path(path).expanduser().resolve()
    if not source.is_file():
        raise FileNotFoundError(f"evidence table not found: {source}")
    if source.suffix.lower() in {".parquet", ".pq"}:
        frame = pd.read_parquet(source)
    elif source.suffix.lower() in {".tsv", ".txt"}:
        frame = pd.read_csv(source, sep="\t")
    else:
        frame = pd.read_csv(source)
    if frame.empty:
        raise ValueError(f"evidence table is empty: {source}")
    return frame, source, sha256(source.read_bytes()).hexdigest()


def _require_columns(frame: pd.DataFrame, columns: Sequence[str], label: str) -> None:
    missing = [column for column in columns if column not in frame.columns]
    if missing:
        raise ValueError(f"{label} evidence is missing required columns: {missing}")


def _finish_figure(fig: plt.Figure, output: Path) -> Path:
    fig.savefig(output, dpi=300, bbox_inches="tight")
    plt.close(fig)
    return output


def plot_foundation_arena_radar(
    output_path: Path | str,
    evaluation_artifacts: Sequence[Path | str] | None = None,
) -> Path:
    """Plot within-benchmark normalized scores from real arena artifacts.

    The radial values are min-max normalized only across the supplied models.
    They are not absolute performance percentages and must not be interpreted
    as clinical superiority.
    """

    artifacts = list(evaluation_artifacts or [])
    if len(artifacts) < 2:
        raise ValueError(
            "foundation radar requires at least two measured evaluation artifacts"
        )
    output = _resolve_output(output_path)
    report = run_foundation_model_arena(
        output_dir=output.parent / "foundation_arena_evidence",
        evaluation_artifacts=artifacts,
    )
    models = list(report.models)
    metric_names = sorted(set.intersection(*(set(model.metrics) for model in models)))
    if len(metric_names) < 3:
        raise ValueError("foundation radar requires at least three shared metrics")

    raw = np.array(
        [[model.metrics[name].value for name in metric_names] for model in models],
        dtype=float,
    )
    if not np.isfinite(raw).all():
        raise ValueError("foundation arena metrics must be finite")
    normalized = np.empty_like(raw)
    for column, name in enumerate(metric_names):
        values = raw[:, column]
        span = float(np.ptp(values))
        if span == 0.0:
            normalized[:, column] = 50.0
        else:
            scaled = 100.0 * (values - values.min()) / span
            if models[0].metrics[name].direction == "lower":
                scaled = 100.0 - scaled
            normalized[:, column] = scaled

    apply_scientific_plot_style()
    count = len(metric_names)
    angles = np.linspace(0.0, 2.0 * np.pi, count, endpoint=False).tolist()
    closed_angles = angles + angles[:1]
    fig, raw_ax = plt.subplots(
        figsize=(9.2, 8.2), subplot_kw={"polar": True}, dpi=300
    )
    ax = cast(PolarAxes, raw_ax)
    ax.set_ylim(0, 100)
    ax.set_yticks([25, 50, 75, 100])
    ax.set_yticklabels(["25", "50", "75", "100"])
    ax.set_xticks(angles)
    ax.set_xticklabels([name.replace("_", " ") for name in metric_names])
    palette = plt.get_cmap("tab10")
    for index, model in enumerate(models):
        values = normalized[index].tolist()
        closed = values + values[:1]
        color = palette(index % 10)
        ax.plot(closed_angles, closed, linewidth=2.0, label=model.model_name, color=color)
        ax.fill(closed_angles, closed, alpha=0.08, color=color)
    ax.set_title(
        "Foundation-model benchmark\n"
        "Within-benchmark min-max normalization (descriptive only)",
        pad=24,
    )
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.10), ncol=2)
    fig.text(
        0.5,
        0.015,
        f"Benchmark: {report.benchmark_id} | group-disjoint evidence | "
        "radial scores are relative, not clinical percentages",
        ha="center",
        fontsize=8,
        color="#475569",
    )
    return _finish_figure(fig, output)


def plot_confounder_cosine_analysis(
    output_path: Path | str,
    evidence_path: Path | str | None = None,
) -> Path:
    """Plot measured confounder-pair embeddings from a long-format table."""

    if evidence_path is None:
        raise ValueError("confounder plot requires an evidence CSV or Parquet file")
    frame, source, source_hash = _read_evidence_table(evidence_path)
    required = ["model_name", "si_ratio", "embedding_cosine_similarity"]
    _require_columns(frame, required, "confounder")
    clean = frame[required].copy()
    clean["model_name"] = clean["model_name"].astype(str)
    clean["si_ratio"] = pd.to_numeric(clean["si_ratio"], errors="coerce")
    clean["embedding_cosine_similarity"] = pd.to_numeric(
        clean["embedding_cosine_similarity"], errors="coerce"
    )
    clean = clean.dropna()
    if clean.empty:
        raise ValueError("confounder evidence contains no complete numeric rows")
    if (clean["si_ratio"] <= 0).any():
        raise ValueError("si_ratio must be positive")
    if not clean["embedding_cosine_similarity"].between(-1.0, 1.0).all():
        raise ValueError("embedding cosine similarity must lie in [-1, 1]")

    grouped = clean.groupby("model_name", sort=True)["embedding_cosine_similarity"]
    means = grouped.mean()
    standard_deviation = grouped.std().fillna(0.0)
    counts = grouped.size()
    apply_scientific_plot_style()
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5.2), dpi=300)
    x = np.arange(len(means))
    colors = [plt.get_cmap("tab10")(index % 10) for index in range(len(means))]
    ax1.bar(x, means.to_numpy(), yerr=standard_deviation.to_numpy(), color=colors, capsize=4)
    ax1.set_xticks(x)
    ax1.set_xticklabels(
        [f"{name}\n(n={int(counts[name])})" for name in means.index], rotation=15, ha="right"
    )
    ax1.set_ylabel("Embedding cosine similarity")
    ax1.set_ylim(-1.05, 1.05)
    ax1.set_title("Measured similarity across physiological pairs")
    ax1.grid(axis="y")

    for index, model_name in enumerate(means.index):
        subset = clean[clean["model_name"] == model_name]
        ax2.scatter(
            subset["si_ratio"],
            subset["embedding_cosine_similarity"],
            label=model_name,
            alpha=0.75,
            color=colors[index],
            s=32,
        )
    ax2.set_xlabel("True insulin-sensitivity ratio used by the benchmark")
    ax2.set_ylabel("Embedding cosine similarity")
    ax2.set_ylim(-1.05, 1.05)
    ax2.set_title("Pair-level evidence")
    ax2.grid(True)
    ax2.legend()
    fig.suptitle("Physiological confounder benchmark (simulation evidence)")
    fig.text(
        0.5,
        0.01,
        f"Source: {source.name} | SHA-256 {source_hash[:16]}... | no synthetic fallback",
        ha="center",
        fontsize=8,
        color="#475569",
    )
    fig.tight_layout(rect=(0, 0.04, 1, 0.96))
    return _finish_figure(fig, _resolve_output(output_path))


def _architecture_box(
    ax: Axes,
    x: float,
    y: float,
    width: float,
    height: float,
    title: str,
    detail: str,
    color: str,
) -> None:
    patch = FancyBboxPatch(
        (x, y),
        width,
        height,
        boxstyle="round,pad=0.012,rounding_size=0.015",
        facecolor="#FFFFFF",
        edgecolor=color,
        linewidth=1.5,
    )
    ax.add_patch(patch)
    ax.text(x + width / 2, y + height * 0.65, title, ha="center", va="center", weight="bold", fontsize=9.5, color="#0F172A")
    ax.text(x + width / 2, y + height * 0.30, detail, ha="center", va="center", fontsize=7.8, color="#475569", linespacing=1.25)


def _arrow(ax: Axes, start: tuple[float, float], end: tuple[float, float]) -> None:
    ax.add_patch(
        FancyArrowPatch(start, end, arrowstyle="-|>", mutation_scale=12, linewidth=1.2, color="#64748B")
    )


def plot_glucofm_dual_stream_decomposition(output_path: Path | str) -> Path:
    """Draw the implemented GlucoFM reproduction architecture as a schematic."""

    apply_scientific_plot_style()
    output = _resolve_output(output_path)
    fig, ax = plt.subplots(figsize=(13, 6.8), dpi=300)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")
    ax.set_title("IINTS GlucoFM v2 independent reproduction: implemented method", pad=18)
    ax.text(
        0.5,
        0.93,
        "Architecture schematic only - not an official Google checkpoint and not a performance result",
        ha="center",
        fontsize=9,
        color="#475569",
    )

    _architecture_box(ax, 0.03, 0.40, 0.14, 0.20, "24 h CGM grid", "288 positions\n5-minute spacing\nphysical missingness mask", "#334155")
    _architecture_box(ax, 0.22, 0.40, 0.16, 0.20, "Causal separation", "mask-aware Gaussian\nsigma constrained to [2, 12]\nmaximum lag: 36 steps", "#0F766E")
    _architecture_box(ax, 0.43, 0.66, 0.16, 0.18, "State stream", "waveform + difference\n+ patch statistics\n24 x 12-point patches", "#2563EB")
    _architecture_box(ax, 0.43, 0.18, 0.16, 0.18, "Event stream", "residual + nearest-observed ROC\n+ patch statistics\n24 x 12-point patches", "#B45309")
    _architecture_box(ax, 0.64, 0.40, 0.14, 0.20, "Token fusion", "64D state + 64D event\n-> fused 128D tokens\n+ circular time encoding", "#7C3AED")
    _architecture_box(ax, 0.83, 0.40, 0.14, 0.20, "Context encoder", "3 transformer layers\n4 attention heads\nFF dimension 256\nmean -> 128D embedding", "#166534")

    _arrow(ax, (0.17, 0.50), (0.22, 0.50))
    _arrow(ax, (0.38, 0.53), (0.43, 0.71))
    _arrow(ax, (0.38, 0.47), (0.43, 0.27))
    _arrow(ax, (0.59, 0.75), (0.64, 0.55))
    _arrow(ax, (0.59, 0.27), (0.64, 0.45))
    _arrow(ax, (0.78, 0.50), (0.83, 0.50))

    ax.text(
        0.5,
        0.07,
        "Self-supervision: masked-context regression + temporal-dynamics objective + EMA target encoder\n"
        "Reusable research embeddings require a trained, provenance-bearing checkpoint.",
        ha="center",
        va="center",
        fontsize=8.5,
        color="#334155",
        bbox={"boxstyle": "round,pad=0.5", "facecolor": "#F8FAFC", "edgecolor": "#CBD5E1"},
    )
    return _finish_figure(fig, output)


def plot_cgmacros_dualsensor_comparison(
    output_path: Path | str,
    evidence_path: Path | str | None = None,
) -> Path:
    """Plot paired Dexcom/Libre measurements from an explicit evidence table."""

    if evidence_path is None:
        raise ValueError("dual-sensor plot requires a paired evidence table")
    frame, source, source_hash = _read_evidence_table(evidence_path)
    required = ["timestamp", "dexcom_mgdl", "libre_mgdl", "cohort"]
    _require_columns(frame, required, "dual-sensor")
    clean = frame[required].copy()
    clean["timestamp"] = pd.to_datetime(clean["timestamp"], errors="coerce")
    clean["dexcom_mgdl"] = pd.to_numeric(clean["dexcom_mgdl"], errors="coerce")
    clean["libre_mgdl"] = pd.to_numeric(clean["libre_mgdl"], errors="coerce")
    clean = clean.dropna()
    if clean.empty:
        raise ValueError("dual-sensor evidence contains no complete paired rows")
    clean["minute_of_day"] = clean["timestamp"].dt.hour * 60 + clean["timestamp"].dt.minute
    cohorts = sorted(clean["cohort"].astype(str).unique())
    fig, axes_raw = plt.subplots(1, len(cohorts), figsize=(5.2 * len(cohorts), 4.8), squeeze=False, dpi=300)
    axes = axes_raw[0]
    apply_scientific_plot_style()
    for ax, cohort in zip(axes, cohorts):
        subset = clean[clean["cohort"].astype(str) == cohort]
        aggregate = subset.groupby("minute_of_day")[["dexcom_mgdl", "libre_mgdl"]].median().sort_index()
        hours = aggregate.index.to_numpy(dtype=float) / 60.0
        ax.plot(hours, aggregate["dexcom_mgdl"], label="Dexcom median", color="#2563EB")
        ax.plot(hours, aggregate["libre_mgdl"], label="Libre median", color="#C2410C")
        mean_absolute_delta = float(np.mean(np.abs(subset["dexcom_mgdl"] - subset["libre_mgdl"])))
        ax.set_title(f"{cohort}\npaired rows n={len(subset):,}; mean |delta|={mean_absolute_delta:.1f} mg/dL")
        ax.set_xlabel("Time of day (h)")
        ax.set_ylabel("Glucose (mg/dL)")
        ax.grid(True)
        ax.legend()
    fig.suptitle("Paired dual-sensor evidence (descriptive medians)")
    fig.text(0.5, 0.01, f"Source: {source.name} | SHA-256 {source_hash[:16]}...", ha="center", fontsize=8, color="#475569")
    fig.tight_layout(rect=(0, 0.04, 1, 0.94))
    return _finish_figure(fig, _resolve_output(output_path))


def plot_fda_safety_mitigation_timeline(
    output_path: Path | str,
    evidence_path: Path | str | None = None,
) -> Path:
    """Plot a measured in-silico safety benchmark trace.

    Despite the legacy function name, this figure does not claim that a
    simulator trace is FDA validation or a reproduced adverse event.
    """

    if evidence_path is None:
        raise ValueError("safety timeline requires an in-silico benchmark trace")
    frame, source, source_hash = _read_evidence_table(evidence_path)
    required = ["time_minutes", "unsupervised_glucose_mgdl", "supervised_glucose_mgdl"]
    _require_columns(frame, required, "safety timeline")
    clean = frame[required].apply(pd.to_numeric, errors="coerce").dropna().sort_values("time_minutes")
    if len(clean) < 2:
        raise ValueError("safety timeline requires at least two complete rows")
    apply_scientific_plot_style()
    fig, ax = plt.subplots(figsize=(10.5, 5.2), dpi=300)
    ax.axhspan(0, 54, color="#FEE2E2", alpha=0.65, label="Very low glucose band (<54 mg/dL)")
    ax.axhspan(70, 180, color="#DCFCE7", alpha=0.45, label="Target range (70-180 mg/dL)")
    ax.plot(clean["time_minutes"], clean["unsupervised_glucose_mgdl"], color="#B91C1C", label="Comparator trace")
    ax.plot(clean["time_minutes"], clean["supervised_glucose_mgdl"], color="#047857", label="Supervisor trace")
    ax.set_xlabel("Simulation time (minutes)")
    ax.set_ylabel("Simulated glucose (mg/dL)")
    ax.set_title("Deterministic safety benchmark - in silico trace")
    ax.grid(True)
    ax.legend()
    fig.text(
        0.5,
        0.01,
        f"Source: {source.name} | SHA-256 {source_hash[:16]}... | not clinical or FDA validation",
        ha="center",
        fontsize=8,
        color="#475569",
    )
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    return _finish_figure(fig, _resolve_output(output_path))


def _dashboard_card(title: str, description: str, path: Path | None) -> str:
    if path is None:
        return (
            '<section class="card card--missing"><h2>'
            + escape(title)
            + "</h2><p>Not generated: no evidence artifact was supplied.</p></section>"
        )
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return (
        '<section class="card"><h2>'
        + escape(title)
        + '</h2><img alt="'
        + escape(title)
        + '" src="data:image/png;base64,'
        + encoded
        + '"><p>'
        + escape(description)
        + "</p></section>"
    )


def generate_interactive_dashboard_html(
    output_path: Path | str,
    radar_img_path: Path | None,
    confounder_img_path: Path | None,
    glucofm_img_path: Path,
    cgmacros_img_path: Path | None,
    fda_img_path: Path | None,
) -> Path:
    """Generate a standalone dashboard that distinguishes methods from evidence."""

    output = _resolve_output(output_path)
    cards = [
        _dashboard_card("GlucoFM reproduction architecture", "Implemented method schematic; not an experimental result.", glucofm_img_path),
        _dashboard_card("Foundation-model comparison", "Measured models evaluated under one group-disjoint benchmark contract.", radar_img_path),
        _dashboard_card("Physiological confounder analysis", "Pair-level simulation evidence loaded from a traceable table.", confounder_img_path),
        _dashboard_card("Paired dual-sensor analysis", "Descriptive statistics computed from supplied paired measurements.", cgmacros_img_path),
        _dashboard_card("Safety benchmark trace", "In-silico comparison; not clinical or regulatory validation.", fda_img_path),
    ]
    output.write_text(
        """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IINTS-AF evidence figures</title><style>body{font:15px/1.5 Georgia,serif;margin:0;background:#f8fafc;color:#0f172a}main{max-width:1200px;margin:auto;padding:28px}header{border-bottom:3px solid #334155;margin-bottom:22px}h1{font-size:27px}.notice{background:#fff7ed;border:1px solid #fdba74;padding:12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(420px,1fr));gap:18px}.card{background:white;border:1px solid #cbd5e1;padding:16px}.card--missing{background:#f1f5f9;color:#475569}.card h2{font-size:18px;margin-top:0}.card img{width:100%;height:auto;border:1px solid #e2e8f0}</style></head><body><main><header><h1>IINTS-AF Scientific Visualization Suite</h1><p>Method diagrams and evidence-backed result figures are kept separate.</p></header><p class="notice">Missing evidence is shown as missing. The dashboard never replaces it with synthetic scores.</p><div class="grid">"""
        + "".join(cards)
        + "</div></main></body></html>",
        encoding="utf-8",
    )
    return output


def generate_all_scientific_visualizations(
    output_dir: Path | str = "results/scientific_visualizations",
    *,
    arena_evaluation_artifacts: Sequence[Path | str] | None = None,
    confounder_evidence: Path | str | None = None,
    cgmacros_evidence: Path | str | None = None,
    safety_trace: Path | str | None = None,
) -> ScientificVisualizationArtifacts:
    """Generate a method schematic plus only those figures backed by inputs."""

    output = Path(output_dir).expanduser().resolve()
    figure_dir = output / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    glucofm = plot_glucofm_dual_stream_decomposition(
        figure_dir / "glucofm_method_schematic.png"
    )
    arena = (
        plot_foundation_arena_radar(
            figure_dir / "foundation_arena_radar.png", arena_evaluation_artifacts
        )
        if arena_evaluation_artifacts
        else None
    )
    confounder = (
        plot_confounder_cosine_analysis(
            figure_dir / "confounder_cosine_analysis.png", confounder_evidence
        )
        if confounder_evidence is not None
        else None
    )
    dual_sensor = (
        plot_cgmacros_dualsensor_comparison(
            figure_dir / "paired_dual_sensor.png", cgmacros_evidence
        )
        if cgmacros_evidence is not None
        else None
    )
    safety = (
        plot_fda_safety_mitigation_timeline(
            figure_dir / "safety_benchmark_trace.png", safety_trace
        )
        if safety_trace is not None
        else None
    )
    dashboard = generate_interactive_dashboard_html(
        output / "index.html", arena, confounder, glucofm, dual_sensor, safety
    )
    return ScientificVisualizationArtifacts(
        output_dir=output,
        arena_radar_png=arena,
        confounder_cosine_png=confounder,
        glucofm_decomposition_png=glucofm,
        cgmacros_dualsensor_png=dual_sensor,
        fda_safety_timeline_png=safety,
        interactive_dashboard_html=dashboard,
    )


__all__ = [
    "ScientificVisualizationArtifacts",
    "apply_scientific_plot_style",
    "plot_foundation_arena_radar",
    "plot_confounder_cosine_analysis",
    "plot_glucofm_dual_stream_decomposition",
    "plot_cgmacros_dualsensor_comparison",
    "plot_fda_safety_mitigation_timeline",
    "generate_interactive_dashboard_html",
    "generate_all_scientific_visualizations",
]
