#!/usr/bin/env python3
"""
MATLAB Control Theory Integration - IINTS-AF
Exports AI decision data for advanced stability analysis in MATLAB
"""

import pandas as pd
import numpy as np
from pathlib import Path
import json
from scipy.io import savemat
from datetime import datetime

class MATLABControlAnalyzer:
    def __init__(self):
        self.results_dir = Path("results")
        self.matlab_dir = Path("results/matlab_analysis")
        self.matlab_dir.mkdir(exist_ok=True)
        
    def export_control_data(self):
        """Export AI decision data for MATLAB control theory analysis"""
        
        # Load latest Excel summary
        excel_files = list(self.results_dir.glob("IINTS_Summary_*.xlsx"))
        if not excel_files:
            print("No Excel summary found. Generate one first.")
            return
        
        latest_excel = max(excel_files, key=lambda p: p.stat().st_mtime)
        
        # Load decision audit data
        decision_df = pd.read_excel(latest_excel, sheet_name='Decision_Audit')
        
        # Prepare control system data
        control_data = self._prepare_control_matrices(decision_df)
        
        # Export to MATLAB format
        matlab_file = self.matlab_dir / f"control_analysis_{datetime.now().strftime('%Y%m%d_%H%M')}.mat"
        
        savemat(matlab_file, control_data)
        
        # Generate MATLAB analysis script
        self._generate_matlab_script()
        
        print(f"MATLAB control data exported: {matlab_file}")
        print(f"MATLAB script generated: {self.matlab_dir}/analyze_stability.m")
        
        return matlab_file
    
    def _prepare_control_matrices(self, decision_df):
        """Prepare data matrices for MATLAB control analysis"""
        
        # Extract time series data
        glucose = decision_df['Glucose_mg_dL'].values
        insulin = decision_df['Insulin_Dose_U'].values
        confidence = decision_df['Confidence_Score'].values
        
        # Calculate glucose rate of change (derivative)
        glucose_rate = np.gradient(glucose)
        
        # Create control system matrices
        # State: [glucose, glucose_rate]
        # Input: insulin_dose
        # Output: glucose
        
        n_samples = len(glucose)
        
        # System identification data
        control_data = {
            'glucose_mg_dL': glucose,
            'insulin_dose_U': insulin,
            'glucose_rate': glucose_rate,
            'ai_confidence': confidence,
            'time_minutes': np.arange(0, n_samples * 5, 5),  # 5-minute intervals
            'sampling_time': 5.0,  # minutes
            'target_glucose': 120.0,  # mg/dL
            'safe_range_low': 70.0,
            'safe_range_high': 180.0,
            'patient_id': '559',
            'algorithm': 'lstm_learned',
            'n_samples': n_samples
        }
        
        # Add stability metrics
        control_data.update(self._calculate_stability_metrics(glucose, insulin))
        
        return control_data
    
    def _calculate_stability_metrics(self, glucose, insulin):
        """Calculate preliminary stability metrics"""
        
        # Glucose variability
        cv_glucose = (np.std(glucose) / np.mean(glucose)) * 100
        
        # Control effort (insulin variability)
        insulin_variability = np.std(np.diff(insulin))
        
        # Overshoot analysis
        target = 120.0
        overshoot_events = np.sum(glucose > 180.0)
        undershoot_events = np.sum(glucose < 70.0)
        
        # Settling time estimation (time to reach ±10% of target)
        settling_band = 0.1 * target  # 12 mg/dL
        
        return {
            'cv_glucose_percent': cv_glucose,
            'insulin_variability': insulin_variability,
            'overshoot_events': overshoot_events,
            'undershoot_events': undershoot_events,
            'settling_band_mg_dL': settling_band,
            'mean_glucose': np.mean(glucose),
            'std_glucose': np.std(glucose)
        }
    
    def _generate_matlab_script(self):
        """Generate MATLAB script for control theory analysis"""
        
        matlab_script = '''%% IINTS-AF Control Theory Analysis
%% Stability Analysis of AI-based Glucose Control System
%% Generated by IINTS-AF Framework

clear; clc; close all;

%% Load Control Data
fprintf('Loading IINTS-AF control data...\\n');
data_files = dir('control_analysis_*.mat');
if isempty(data_files)
    error('No control analysis data found. Run Python export first.');
end

% Load most recent data file
[~, idx] = max([data_files.datenum]);
load(data_files(idx).name);

fprintf('Loaded data for Patient %s using %s algorithm\\n', patient_id, algorithm);
fprintf('Analysis period: %d samples (%.1f hours)\\n', n_samples, n_samples*sampling_time/60);

%% 1. System Identification
fprintf('\\n=== SYSTEM IDENTIFICATION ===\\n');

% Create input-output data for system identification
glucose_normalized = (glucose_mg_dL - target_glucose) / target_glucose;
insulin_normalized = insulin_dose_U / max(insulin_dose_U);

% Estimate transfer function using System Identification Toolbox
if exist('tfest', 'file')
    % Create iddata object
    data_id = iddata(glucose_normalized, insulin_normalized, sampling_time);
    
    % Estimate 2nd order transfer function
    sys_tf = tfest(data_id, 2, 1);
    
    fprintf('Estimated Transfer Function:\\n');
    sys_tf
    
    % Calculate stability margins
    [Gm, Pm, Wcg, Wcp] = margin(sys_tf);
    fprintf('Gain Margin: %.2f dB (%.2f)\\n', 20*log10(Gm), Gm);
    fprintf('Phase Margin: %.2f degrees\\n', Pm);
    
    % Stability assessment
    if Pm > 45 && Gm > 6
        stability_status = 'STABLE';
    elseif Pm > 30 && Gm > 3
        stability_status = 'MARGINALLY STABLE';
    else
        stability_status = 'POTENTIALLY UNSTABLE';
    end
    fprintf('Stability Assessment: %s\\n', stability_status);
else
    fprintf('System Identification Toolbox not available.\\n');
    fprintf('Using basic analysis...\\n');
    stability_status = 'ANALYSIS LIMITED';
end

%% 2. Frequency Domain Analysis
fprintf('\\n=== FREQUENCY DOMAIN ANALYSIS ===\\n');

% Create Bode plot
figure('Name', 'IINTS-AF Bode Plot', 'Position', [100, 100, 1200, 800]);

if exist('bode', 'file') && exist('sys_tf', 'var')
    subplot(2,2,1);
    bode(sys_tf);
    title('Bode Plot - AI Glucose Control System');
    grid on;
    
    subplot(2,2,2);
    step(sys_tf);
    title('Step Response');
    ylabel('Normalized Glucose Response');
    xlabel('Time (minutes)');
    grid on;
else
    % Manual frequency analysis
    subplot(2,2,1);
    frequencies = logspace(-3, 0, 100);  % 0.001 to 1 rad/min
    
    % Simple frequency response estimation
    glucose_fft = fft(glucose_normalized);
    insulin_fft = fft(insulin_normalized);
    
    % Avoid division by zero
    insulin_fft(abs(insulin_fft) < 1e-10) = 1e-10;
    
    freq_response = glucose_fft ./ insulin_fft;
    freq_axis = (0:length(freq_response)-1) * (2*pi) / (n_samples * sampling_time);
    
    semilogx(freq_axis(1:floor(end/2)), abs(freq_response(1:floor(end/2))));
    title('Frequency Response Magnitude');
    xlabel('Frequency (rad/min)');
    ylabel('Magnitude');
    grid on;
    
    subplot(2,2,2);
    plot(time_minutes, glucose_mg_dL, 'b-', 'LineWidth', 2);
    hold on;
    yline(target_glucose, 'r--', 'Target', 'LineWidth', 2);
    yline(safe_range_high, 'r:', 'Upper Limit', 'LineWidth', 1);
    yline(safe_range_low, 'r:', 'Lower Limit', 'LineWidth', 1);
    title('Glucose Time Response');
    xlabel('Time (minutes)');
    ylabel('Glucose (mg/dL)');
    legend('Actual', 'Target', 'Safety Limits');
    grid on;
end

%% 3. Performance Metrics
subplot(2,2,3);
histogram(glucose_mg_dL, 20, 'FaceColor', [0.2, 0.6, 0.8], 'EdgeColor', 'black');
xline(target_glucose, 'r--', 'Target', 'LineWidth', 2);
xline(safe_range_low, 'r:', 'LineWidth', 2);
xline(safe_range_high, 'r:', 'LineWidth', 2);
title('Glucose Distribution');
xlabel('Glucose (mg/dL)');
ylabel('Frequency');
grid on;

subplot(2,2,4);
plot(time_minutes, ai_confidence, 'g-', 'LineWidth', 2);
title('AI Confidence Over Time');
xlabel('Time (minutes)');
ylabel('Confidence Score');
ylim([0, 1]);
grid on;

%% 4. Generate Report
fprintf('\\n=== CONTROL THEORY REPORT ===\\n');
fprintf('Patient ID: %s\\n', patient_id);
fprintf('Algorithm: %s\\n', algorithm);
fprintf('Analysis Duration: %.1f hours\\n', n_samples*sampling_time/60);
fprintf('\\nPERFORMANCE METRICS:\\n');
fprintf('- Mean Glucose: %.1f mg/dL\\n', mean_glucose);
fprintf('- Glucose CV: %.1f%%\\n', cv_glucose_percent);
fprintf('- Hypoglycemic Events: %d\\n', undershoot_events);
fprintf('- Hyperglycemic Events: %d\\n', overshoot_events);
fprintf('- Control Effort (Insulin Variability): %.3f\\n', insulin_variability);

if exist('sys_tf', 'var')
    fprintf('\\nSTABILITY ANALYSIS:\\n');
    fprintf('- Gain Margin: %.2f dB\\n', 20*log10(Gm));
    fprintf('- Phase Margin: %.2f degrees\\n', Pm);
    fprintf('- Stability Status: %s\\n', stability_status);
end

fprintf('\\nCONCLUSION:\\n');
if cv_glucose_percent < 36 && undershoot_events == 0
    fprintf('EXCELLENT: Low variability with no hypoglycemic events\\n');
elseif cv_glucose_percent < 36
    fprintf('GOOD: Acceptable glucose control with minimal safety events\\n');
else
    fprintf('NEEDS IMPROVEMENT: High glucose variability detected\\n');
end

%% Save Results
save('iints_control_analysis_results.mat', 'stability_status', 'cv_glucose_percent', ...
     'mean_glucose', 'overshoot_events', 'undershoot_events');

% Save figure
saveas(gcf, 'IINTS_Control_Analysis.png');
fprintf('\\nResults saved to: iints_control_analysis_results.mat\\n');
fprintf('Figure saved to: IINTS_Control_Analysis.png\\n');

fprintf('\\n=== ANALYSIS COMPLETE ===\\n');
'''
        
        script_file = self.matlab_dir / "analyze_stability.m"
        with open(script_file, 'w') as f:
            f.write(matlab_script)
        
        return script_file

def main():
    analyzer = MATLABControlAnalyzer()
    
    print("IINTS-AF MATLAB Control Theory Integration")
    print("=========================================")
    
    try:
        matlab_file = analyzer.export_control_data()
        
        print(f"\nMATLAB integration ready!")
        print(f"\nNext steps:")
        print(f"1. Open MATLAB")
        print(f"2. Navigate to: results/matlab_analysis/")
        print(f"3. Run: analyze_stability")
        print(f"\nThis will generate:")
        print(f"- Bode plots (frequency response)")
        print(f"- Stability margins (gain/phase)")
        print(f"- Step response analysis")
        print(f"- Professional control theory report")
        
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()
