"""Small, stable navigation helpers for the public CLI."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
import typer


@dataclass(frozen=True)
class CommandDomain:
    title: str
    commands: tuple[str, ...]
    purpose: str


# This is intentionally a small navigation layer, not a second copy of every
# option generated by Typer.
COMMAND_DOMAINS = (
    CommandDomain(
        "Simulation and studies",
        (
            "iints demo",
            "iints presets list",
            "iints run --preset baseline_t1d --dry-run",
            "iints run-study --help",
        ),
        "Run inspectable virtual-patient protocols and reproducible comparison studies.",
    ),
    CommandDomain(
        "Models and physiology",
        (
            "iints profiles presets",
            "iints patientmodel list",
            "iints research regenerative panels",
            "iints research regenerative compare --help",
            "iints research regenerative import-proteomics --help",
            "iints research mechanistic --help",
            "iints research cellml --help",
        ),
        "Inspect patient profiles, SC-islet protein evidence panels, and independent mechanistic-model workflows.",
    ),
    CommandDomain(
        "Results and evidence",
        (
            "iints results <run-dir>",
            "iints analyze <study-dir>",
            "iints poster-study <study-dir>",
            "iints evidence build --run baseline=results/baseline",
        ),
        "Review metrics, compare runs, and package traceable research artifacts.",
    ),
    CommandDomain(
        "Data and MDMP",
        (
            "iints data validate --help",
            "iints data pull-safe --help",
            "iints data import-cgmacros --help",
            "iints data download-cgmacros --help",
            "iints mdmp template",
            "iints mdmp run-gate --help",
            "iints mdmp sign --help",
            "iints mdmp verify --help",
            "iints mdmp validate --help",
        ),
        "Validate contracts, protect local files, and import standardized clinical datasets (CGMacros).",
    ),
    CommandDomain(
        "AI and algorithms",
        (
            "iints new-algo --help",
            "iints algorithms list",
            "iints ai --help",
            "iints research glucose-model --help",
            "iints research ppgr-benchmark --help",
            "iints research glucofm-embed --help",
            "iints research foundation-arena --help",
            "iints research cgm-jepa-embed --help",
            "iints research cgm-jepa-experiment --help",
            "iints research cgm-jepa-confounder --help",
        ),
        "Develop controllers, evaluate foundation models (Google GlucoFM, CGM-JEPA), and benchmark latent physiological sensitivity.",
    ),
    CommandDomain(
        "Hardware research",
        (
            "iints edge doctor",
            "iints jetson doctor",
            "iints fpga doctor",
            "iints pump bench-test --help",
        ),
        "Prepare bench-only edge, FPGA, and pump experiments without clinical control claims.",
    ),
    CommandDomain(
        "Medical device safety & FDA verification",
        (
            "iints safety fda-list",
            "iints safety fda-benchmark --help",
        ),
        "Benchmark controllers against real FDA device recalls (Tandem, MiniMed, Omnipod, Dexcom).",
    ),
    CommandDomain(
        "Installation and quality",
        (
            "iints version",
            "iints doctor --suggest",
            "iints validation-profiles",
            "iints golden-benchmark --help",
        ),
        "Check the active environment, available updates, validation profiles, and regressions.",
    ),
)


def show_command_map(console: Optional[Console] = None) -> None:
    """Print the maintained public command families and reliable entry points."""

    target = console or Console()
    target.print()
    target.print(
        Panel(
            "Seven public command domains. Use `--help` on any command for its authoritative options.",
            title="IINTS-AF command map",
            subtitle="Research and education only",
            border_style="cyan",
        )
    )
    table = Table(expand=True, show_lines=True)
    table.add_column("Domain", style="bold white", width=24)
    table.add_column("Reliable entry points", style="cyan", width=45)
    table.add_column("Purpose")
    for domain in COMMAND_DOMAINS:
        table.add_row(domain.title, "\n".join(domain.commands), domain.purpose)
    target.print(table)
    target.print(
        "Use [cyan]iints menu[/cyan] to choose a domain or "
        "[cyan]iints --help[/cyan] for the complete generated command list."
    )


def interactive_menu(console: Optional[Console] = None) -> None:
    """Show navigation without directly invoking Typer command handlers."""

    target = console or Console()
    while True:
        target.print()
        lines = ["Choose a command domain:", ""]
        lines.extend(f"  {index}. {domain.title}" for index, domain in enumerate(COMMAND_DOMAINS, start=1))
        lines.extend(("", "  m. Show the complete command map", "  q. Exit"))
        target.print(Panel("\n".join(lines), title="IINTS-AF navigation", border_style="cyan"))
        choice = typer.prompt("Selection [1-7, m, q]", default="1").strip().lower()
        if choice == "q":
            return
        if choice == "m":
            show_command_map(target)
            continue
        try:
            selected = COMMAND_DOMAINS[int(choice) - 1]
        except (ValueError, IndexError):
            target.print("[red]Unknown selection.[/red]")
            continue
        target.print(
            Panel(
                "\n".join(
                    (*selected.commands, "", "Run any line above, or add `--help` before executing a workflow.")
                ),
                title=selected.title,
                border_style="green",
            )
        )


__all__ = ["COMMAND_DOMAINS", "interactive_menu", "show_command_map"]
