from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional
import json


def _badge_color(grade: str) -> str:
    normalized = grade.strip().lower()
    if normalized == "ai_ready":
        return "green"
    if normalized == "clinical_grade":
        return "teal"
    if normalized == "research_grade":
        return "blue"
    if normalized == "draft":
        return "orange"
    return "lightgrey"


def build_hf_mdmp_section(
    *,
    dataset_id: str,
    grade: str,
    fingerprint: str,
    contract_fingerprint: Optional[str] = None,
    compliance_score: Optional[float] = None,
    protocol_version: Optional[str] = None,
    registry_url: Optional[str] = None,
) -> str:
    color = _badge_color(grade)
    badge = f"https://img.shields.io/badge/MDMP-{grade.replace('_', '%5F')}-{color}"
    registry_line = f"- Registry: {registry_url}" if registry_url else "- Registry: local/private"

    lines = [
        "## MDMP",
        "",
        f"![MDMP]({badge})",
        "",
        f"- Dataset: `{dataset_id}`",
        f"- Grade: `{grade}`",
        f"- Fingerprint: `{fingerprint}`",
    ]
    if contract_fingerprint:
        lines.append(f"- Contract fingerprint: `{contract_fingerprint}`")
    if compliance_score is not None:
        lines.append(f"- Compliance score: `{compliance_score:.2f}`")
    if protocol_version:
        lines.append(f"- Protocol version: `{protocol_version}`")
    lines.append(registry_line)
    lines.append("")
    lines.append("Generated by `mdmp hf-export`.")
    return "\n".join(lines)


def load_report(path: Path) -> Dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("Report must be a JSON object")
    return payload
